### ISSUE TITLE
NPE Thrown if Unit Test Cut Class is not Defined

### ISSUE THREAD

**Issue by saden1** [FitburIO/testify#14]
```
java.lang.NullPointerException
	at com.fitbur.testify.unit.UnitTestVerifier.configuration(UnitTestVerifier.java:78)
	at com.fitbur.testify.junit.UnitTest.run(UnitTest.java:124)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:45)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
```

**Comment by saden1** [comment]
Done.
