### ISSUE TITLE
Testify Doesn't Handle @Ignore

### ISSUE THREAD

**Issue by saden1** [FitburIO/testify#18]
```
java.lang.NullPointerException
	at com.fitbur.testify.integration.SpringIntegrationTestRunListener.done(SpringIntegrationTestRunListener.java:137)
	at com.fitbur.testify.integration.SpringIntegrationTestRunListener.testIgnored(SpringIntegrationTestRunListener.java:133)
	at org.junit.runner.notification.SynchronizedRunListener.testIgnored(SynchronizedRunListener.java:77)
	at org.junit.runner.notification.RunNotifier$6.notifyListener(RunNotifier.java:174)
	at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
	at org.junit.runner.notification.RunNotifier.fireTestIgnored(RunNotifier.java:171)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at com.fitbur.testify.integration.SpringIntegrationTest.run(SpringIntegrationTest.java:149)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
```

**Comment by saden1** [comment]
fixed in release 0.0.6
