### ISSUE TITLE
Incompatible with actual Mockito-versions

### ISSUE THREAD

**Issue by cobour** [FitburIO/testify#35]
Using testify 0.1.3 and mockito-core-2.0.111-beta or -2.1.0 fails, where -2.0.40-beta works.
Error with actual mockito-core versions is:

java.lang.IllegalAccessError: tried to access method org.mockito.internal.util.MockUtil.<init>()V from class com.fitbur.testify.unit.UnitTestReifier
	at com.fitbur.testify.unit.UnitTestReifier.<clinit>(UnitTestReifier.java:45)
	at com.fitbur.testify.junit.UnitTest.methodBlock(UnitTest.java:157)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at com.fitbur.testify.junit.UnitTest.run(UnitTest.java:112)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by saden1** [comment]
Please note that testify now has a new home and and this issue has been resolved in this new version. see http://github.com/testify-project/testiy
